PLAYER_SPEED = 5.0
PLAYER_RADIUS = 0.4
PLAYER_MAX_HEALTH = 100

# --- COD Zombies style economy / shop ---
START_POINTS = 500
POINTS_PER_HIT = 10
POINTS_PER_KILL = 60
POINTS_REPAIR = 10

# Small pause between waves so you can buy stuff
INTERMISSION_SECONDS = 12.0

# Wall-buy costs
COST_SMG = 750
COST_RIFLE = 1400
COST_SHOTGUN = 1200
COST_SNIPER = 2000

# Ammo crate
COST_AMMO_REFILL = 250

# Perk costs
COST_JUGGERNOG = 2500
COST_SPEED_COLA = 2000
COST_DOUBLE_TAP = 2000
COST_STAMIN_UP = 2000

# Perk effects
JUGGERNOG_MAX_HEALTH = 170
SPEED_COLA_RELOAD_MULT = 0.65
DOUBLE_TAP_DAMAGE_MULT = 1.35
STAMIN_UP_SPEED_MULT = 1.25

# Barriers (repairable windows)
BARRIER_MAX_HEALTH = 120.0
BARRIER_REPAIR_AMOUNT = 30.0
BARRIER_ZOMBIE_DAMAGE = 24.0  # damage per second applied when a zombie is hitting a barrier
BARRIER_REPAIR_RADIUS = 1.8

# Weapon ballistics (hitscan)
BULLET_MAX_DISTANCE = 45.0

PISTOL_DAMAGE = 18
PISTOL_FIRE_RATE = 0.25
PISTOL_AMMO = 12
PISTOL_RELOAD_TIME = 1.0

SHOTGUN_DAMAGE = 10
SHOTGUN_PELLETS = 6
SHOTGUN_SPREAD = 0.08
SHOTGUN_FIRE_RATE = 0.9
SHOTGUN_AMMO = 6
SHOTGUN_RELOAD_TIME = 1.4

# More weapons (balanced trade-offs, no "one best" gun)
# - SMG: close range, high spread, good DPS, big mag
# - Rifle: mid range, low spread, steady DPS
# - Sniper: very high damage, slow fire, small mag
SMG_DAMAGE = 6
SMG_FIRE_RATE = 0.085
SMG_AMMO = 30
SMG_RELOAD_TIME = 1.6
SMG_SPREAD = 0.10

RIFLE_DAMAGE = 12
RIFLE_FIRE_RATE = 0.18
RIFLE_AMMO = 24
RIFLE_RELOAD_TIME = 1.4
RIFLE_SPREAD = 0.035

SNIPER_DAMAGE = 50
SNIPER_FIRE_RATE = 1.15
SNIPER_AMMO = 5
SNIPER_RELOAD_TIME = 1.9
SNIPER_SPREAD = 0.008

# Tracers
TRACER_LIFETIME = 0.06
TRACER_THICKNESS = 0.03

ZOMBIE_BASE_SPEED = 1.2
ZOMBIE_BASE_HEALTH = 40
ZOMBIE_ATTACK_DAMAGE = 10
ZOMBIE_ATTACK_RANGE = 0.9
ZOMBIE_ATTACK_COOLDOWN = 1.2

# Zombie variants (balanced)
ZOMBIE_RUNNER_SPEED_MULT = 1.6
ZOMBIE_RUNNER_HEALTH_MULT = 0.75

ZOMBIE_TANK_SPEED_MULT = 0.65
ZOMBIE_TANK_HEALTH_MULT = 2.2

ZOMBIE_SPITTER_SPEED_MULT = 0.95
ZOMBIE_SPITTER_HEALTH_MULT = 0.95
ZOMBIE_SPIT_COOLDOWN = 2.3
ZOMBIE_SPIT_RANGE = 10.0
ZOMBIE_SPIT_DAMAGE = 9

ZOMBIE_BOMBER_SPEED_MULT = 1.05
ZOMBIE_BOMBER_HEALTH_MULT = 1.05
ZOMBIE_BOMB_RANGE = 1.25
ZOMBIE_BOMB_DAMAGE = 28

WAVE_BASE_COUNT = 4
WAVE_GROWTH = 2
WAVE_SPAWN_RADIUS = 8.0

MAP_SIZE = 14.0

# Infinite ground (rendered as tiles around the player)
GROUND_TILE_SIZE = 10.0
GROUND_TILES_RADIUS = 6   # 6 => 13x13 tiles drawn
GROUND_UV_SCALE = 4.0     # texture repeats per tile

# Barriers (repairable)
BARRIER_MAX_HEALTH = 120.0
BARRIER_REPAIR_AMOUNT = 18.0
BARRIER_ZOMBIE_DPS = 22.0
BARRIER_INTERACT_RADIUS = 1.35
